### ISSUE TITLE
Allow / in root key

### ISSUE THREAD

**Issue by leaftail1880** [KalmeMarq/Bugrock-JSON-UI-Schemas#2]
Thanks for such beautifull schema! Im not sure where to find the root key regex so posting it here. 
Currently doing this would be considered as error:
```json
{
  "namespace": "server_form",
 
  // Error here \/
  // Property "custom_dropdown/dropdown" not allowed
  "custom_dropdown/dropdown": { 
    "$dropdown_scroll_content_size": ["100%", "350%"]
  },
}
```

However, it is recommended way to change nested controls.

**Comment by KalmeMarq** [comment]
Done in "allow / in root element names" commit

**Comment by leaftail1880** [comment]
Thank you so much!
